version: '3.3'

services:
  backenddb:
    image: localhost:5000/dp3t-postgres
    environment:
      - POSTGRES_DB=dpppt
      - POSTGRES_USER=dpppt
      - POSTGRES_PASSWORD_FILE=/run/secrets/dp3t_backend_db
      - TZ=WET
    volumes:
      - backenddb:/var/lib/postgresql/data
    secrets:
      - dp3t_backend_db

  backendws:
    image: localhost:5000/dp3t-backendws
    environment:
      - DB_URL=jdbc:postgresql://backenddb:5432/dpppt
      - DB_USER=dpppt
      - DB_PASSWORD_FILE=/run/secrets/dp3t_backend_db
      - BACKEND_PRIVATE_FILE=/run/secrets/dp3t_backend_private
      - BACKEND_PUBLIC_FILE=/run/secrets/dp3t_backend_public
      - JWTTOKEN_PUBLIC_FILE=/run/secrets/dp3t_authtoken_public
      - TZ=WET
    secrets:
      - dp3t_backend_db
      - dp3t_backend_private
      - dp3t_backend_public
      - dp3t_authtoken_public

  keycloakdb:
    image: localhost:5000/dp3t-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD_FILE=/run/secrets/dp3t_keycloak_db
      - TZ=WET
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    secrets:
      - dp3t_keycloak_db

  keycloak:
    image: localhost:5000/dp3t-keycloak
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloakdb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD_FILE=/run/secrets/dp3t_keycloak_db
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD_FILE=/run/secrets/dp3t_keycloak_admin
      - PROXY_ADDRESS_FORWARDING=true
      - TZ=WET
      # Uncomment the following lines for a test user:
      #- BAG_USER=user
      #- BAG_PASSWORD=secret
    ports:
      - "8180:8080"
    secrets:
      - dp3t_keycloak_admin
      - dp3t_keycloak_db

  authcodedb:
    image: localhost:5000/dp3t-postgres
    environment:
      - POSTGRES_DB=haauthcode
      - POSTGRES_USER=haauthcode
      - POSTGRES_PASSWORD_FILE=/run/secrets/dp3t_authcode_db
      - TZ=WET
    volumes:
      - authcodedb:/var/lib/postgresql/data
    secrets:
      - dp3t_authcode_db

  authcodews:
    image: localhost:5000/dp3t-authcodews
    environment:
      - DB_URL=jdbc:postgresql://authcodedb:5432/haauthcode
      - DB_USER=haauthcode
      - DB_PASSWORD_FILE=/run/secrets/dp3t_authcode_db
      - JWTTOKEN_PRIVATE_FILE=/run/secrets/dp3t_authtoken_private
      - TZ=WET
    secrets:
      - dp3t_authcode_db
      - dp3t_authtoken_private

  frontend:
    image: localhost:5000/dp3t-frontend
    volumes:
      - frontend:/data
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=WET

  prometheus:
    image: localhost:5000/dp3t-prom
    build: prometheus
    volumes:
      - prometheus:/prometheus
    ports:
      - "9090:9090"
    environment:
      - TZ=WET

volumes:
  backenddb:
  keycloakdb:
  authcodedb:
  frontend:
  prometheus:

secrets:
  dp3t_keycloak_admin:
    external: true
  dp3t_authtoken_private:
    external: true
  dp3t_backend_private:
    external: true
  dp3t_authtoken_public:
    external: true
  dp3t_backend_public:
    external: true

  dp3t_authcode_db:
    external: true
  dp3t_keycloak_db:
    external: true
  dp3t_backend_db:
    external: true
  
